version: 2
jobs:
  build:
    working_directory: ~/enty
    docker:
      - image: circleci/node:6.10.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - example/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: git diff | cat
      - run: test -z "$(git status --porcelain)"
      - run: yarn test-all
