version: 2.1

executors:
  client_build:
    docker:
      - image: 'blueflag/client-build:0.0.7'

commands:


  #
  # Functions
  #
  restore:
    parameters:
      scope:
        type: 'string'
    steps:
      - restore_cache:
          name: 'Restoring <<parameters.scope>>'
          keys: ['v2-{{ checksum "packages/<<parameters.scope>>/yarn.lock" }}']
  save:
    parameters:
      scope:
        type: 'string'
    steps:
      - save_cache:
          name: 'Saving <<parameters.scope>>'
          key: 'v2-{{ checksum "packages/<<parameters.scope>>/yarn.lock" }}'
          paths: ['packages/<<parameters.scope>>/node_modules']

  #
  # Build Steps
  #
  checkout_and_auth:
    steps:
      - checkout

  restore_all_caches:
    steps:
      - restore_cache: {keys: ['v2-{{ checksum "yarn.lock" }}']}
      - restore: {scope: 'enty'}
      - restore: {scope: 'enty-immutable'}
      - restore: {scope: 'enty-state'}
      - restore: {scope: 'react-enty'}

  save_all_caches:
    steps:
      - save_cache: {key: 'v2-{{ checksum "yarn.lock" }}', paths: ['node_modules']}
      - restore: {scope: 'enty'}
      - restore: {scope: 'enty-immutable'}
      - restore: {scope: 'enty-state'}
      - restore: {scope: 'react-enty'}


  bootstrap_and_test:
    steps:
      - restore_all_caches
      - run: 'yarn prep'
      - run: git diff | cat
      - run: test -z "$(git status --porcelain)"
      - run: 'yarn build'
      - run: 'yarn lerna run test-all --include-filtered-dependents --since origin/master --parallel'
      - save_all_caches

#
# Jobs and Workflows
#
jobs:
  build:
    executor: 'client_build'
    steps:
      - checkout_and_auth
      - bootstrap_and_test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
